set_property IOSTANDARD LVCMOS33 [get_ports {answer_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN A21 [get_ports {answer_led[3]}]
set_property PACKAGE_PIN E22 [get_ports {answer_led[2]}]
set_property PACKAGE_PIN D22 [get_ports {answer_led[1]}]
set_property PACKAGE_PIN E21 [get_ports {answer_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {answer[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports count_down]
set_property IOSTANDARD LVCMOS33 [get_ports No]
set_property IOSTANDARD LVCMOS33 [get_ports Yes]
set_property PACKAGE_PIN T5 [get_ports {answer[0]}]
set_property PACKAGE_PIN T4 [get_ports {answer[1]}]
set_property PACKAGE_PIN R4 [get_ports {answer[2]}]
set_property PACKAGE_PIN W4 [get_ports {answer[3]}]
set_property PACKAGE_PIN A18 [get_ports {seg_en[7]}]
set_property PACKAGE_PIN A20 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN B20 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN E18 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN F18 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN D19 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN E19 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN C19 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN E13 [get_ports {seg_out[7]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN E17 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN F15 [get_ports {seg_out[0]}]




set_property IOSTANDARD LVCMOS33 [get_ports begining]
set_property PACKAGE_PIN Y9 [get_ports begining]
set_property PACKAGE_PIN W9 [get_ports count_down]
set_property PACKAGE_PIN Y8 [get_ports No]
set_property PACKAGE_PIN Y7 [get_ports Yes]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets Yes_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets No_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports time_select]
set_property PACKAGE_PIN AB8 [get_ports time_select]

set_property IOSTANDARD LVCMOS33 [get_ports select1]
set_property PACKAGE_PIN W6 [get_ports select1]

set_property IOSTANDARD LVCMOS33 [get_ports select2]
set_property PACKAGE_PIN U5 [get_ports select2]